# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "lottery-th-dev" do |node|
    node.vm.hostname = "lottery-th-dev"
    node.vm.network :private_network, ip: '192.168.50.100'
    node.hostmanager.aliases = %w(api.lottery-th.local)
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.memory = 2048
    if Vagrant::Util::Platform.windows? and !Vagrant.has_plugin? 'vagrant-winnfsd'
        override.vm.synced_folder "../../", "/home/vagrant/repo", mount_options: ['dmode=755', 'fmode=644']
    else
        override.vm.synced_folder "../../", "/home/vagrant/repo"
    end
  end

  config.vm.provider "libvirt" do |virt, override|
    virt.memory = 2048
    override.vm.synced_folder "../../", "/home/vagrant/repo", :nfs => true
  end

  config.ssh.forward_agent = true

  config.vm.provision :docker
  config.vm.provision :docker_compose
end
